name: tv
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  extended_image: ^7.0.2
  flutter:
    sdk: flutter
  # flutter_gen: ^5.2.0
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.2
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.0
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
flutter_gen:
  output: lib/app/generated/
  integrations:
    flutter_svg: true
